name: clear
on:
  workflow_dispatch: #github页面手动触发
  schedule:
    - cron: '0 0 1 * *' #每月1号0点执行,注意,这是UTC时间,比北京时间晚8个小时,无奈实现不了北京时间1号0点
jobs:
  clear:
    runs-on: ubuntu-latest #虚拟环境(github提供)
    env:
      TZ: Asia/Shanghai
    steps:

      - name: clear-data
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ vars.PORT }}
          script: |
            docker exec go /bin/bash -c 'chmod +x server && ./server -a clear && exit'
